# -*- coding: utf-8 -*-
"""TF_Hello_World.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z2XZ3jyWk6jsyRN4FVIFjB5pJ0Q_rjkM
"""

import tensorflow as tf
import numpy as np
from tensorflow import keras
# print(tf.__version__)

# !pip install tensorflow==2.0.0-rc0

model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

model.compile(optimizer='sgd', loss='mean_squared_error')

xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype = float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype = float)

model.fit(xs,ys, epochs=500)

print(model.predict([10.0]))

# !pip install tensorflow==2.0.0-alpha0 
# !pip install tensorflow==2.0.0-rc0